name: guessita
version: '2.1.4'
summary: python library extractor
description: |
    GuessIta is a python library that extracts as much information as possible from a video filename.
grade: stable
confinement: strict

parts:
  guessita:
    source: https://github.com/heesen3/guessita.git
    source-tag: 2.1.4
    plugin: python
apps:
  guessita:
    command: guessita
apps:
  guessita:
    command: guessita
    plugs: [network]
